language: node_js

node_js:
 - iojs
 - 0.10
 - 0.11
 - 0.12

script: npm test

after_script:
  - npm run coverage
  - npm run codeclimate

webhooks:
  urls:
    - https://webhooks.gitter.im/e/c59c50e0fd30dff70a23
  on_success: change
  on_failure: always
  on_start: false
