sudo: false

language: node_js

node_js:
 - 0.10
 - 0.12
 - 4.0
 - 5.0

cache:
  directories:
    - node_modules

after_script:
  - npm run coverage
  - npm run codeclimate

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c59c50e0fd30dff70a23
    on_success: always
    on_failure: always
    on_start: false
